name = "JPEC"
uuid = "462872dd-e066-4d2e-b993-6468b5239634"
authors = ["Rithik Banerjee <rb3736@columbia.edu>", "Daniel Burgess <daniel.burgess@columbia.edu>", "Evan Bursch <emb2333@columbia.edu>", "Jaebeom Cho <aspire1019@snu.ac.kr>", "Jacob Halpern <jmh2363@columbia.edu>", "Nikolas Logan <nikolas.logan@columbia.edu>", "Brendan C. Lyons <bclyons12@gmail.com>", "Matthew Pharr <matthewcpharr@gmail.com>", "Sunjae Lee <satelite2517@gmail.com>", "Aaron Froese <aaron.froese@generalfusion.com>"]
version = "0.1.0"
license = 'MIT'

[deps]
DiffEqCallbacks = "459566f4-90b8-5000-8ac3-15dfb0a30def"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
DiffEqCallbacks = "4.9.0"
Documenter = "1.14.1"
FFTW = "1.9.0"
HDF5 = "0.17.2"
LinearAlgebra = "1.11.0"
OrdinaryDiffEq = "6.102.0"
Pkg = "1.11.0"
Plots = "1.40.15"
Printf = "1.11.0"
TOML = "1.0.3"
Test = "1.11.0"
