name = "JPEC"
uuid = "462872dd-e066-4d2e-b993-6468b5239634"
authors = ["Matthew Pharr <matthewcpharr@gmail.com>"]
version = "0.1.0"

[deps]
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[compat]
DifferentialEquations = "7.16.1"
LinearAlgebra = "1.11.0"
Plots = "1.40.15"
Printf = "1.11.0"
