name = "JPEC"
uuid = "462872dd-e066-4d2e-b993-6468b5239634"
authors = ["Matthew Pharr <matthewcpharr@gmail.com>", "JayMyoung Lee <jmlmir@snu.ac.kr>"]
version = "0.1.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
BenchmarkTools = "1.6.0"
Plots = "1.40.15"
